import { describe, expect, it, vi } from 'vitest';
import { normalizeAPIBase, PAIRING_PREFIX, parsePairingInput } from './pairing.js';

function toBase64URL(value: string): string {
  return btoa(unescape(encodeURIComponent(value)))
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '');
}

describe('browser extension pairing input', () => {
  it('normalizes a manually entered code and API origin', () => {
    expect(parsePairingInput('abcde-fghjk', 'http://127.0.0.1:8000/')).toEqual({
      v: 1,
      apiBase: 'http://127.0.0.1:8000',
      code: 'ABCDE-FGHJK',
    });
  });

  it('parses the one-paste connection payload generated by Admin', () => {
    const encoded = toBase64URL(
      JSON.stringify({ v: 1, apiBase: 'https://trade.example.com/', code: 'ABCDE-FGHJK' }),
    );
    expect(parsePairingInput(`${PAIRING_PREFIX}${encoded}`, 'http://unused.test')).toEqual({
      v: 1,
      apiBase: 'https://trade.example.com',
      code: 'ABCDE-FGHJK',
    });
  });

  it('rejects non-http API schemes', () => {
    expect(() => normalizeAPIBase('file:///tmp/trademind')).toThrow(/http/);
  });

  it('requires HTTPS for non-loopback TradeMind origins', () => {
    expect(() => normalizeAPIBase('http://trade.example.com')).toThrow(/HTTPS/);
    expect(normalizeAPIBase('http://localhost:8000/')).toBe('http://localhost:8000');
  });

  it('does not include token-shaped values in parse errors', () => {
    vi.stubGlobal('atob', () => {
      throw new Error('decode');
    });
    expect(() => parsePairingInput(`${PAIRING_PREFIX}secret-device-token`, 'http://localhost')).toThrow(
      '连接信息格式无效，请在管理端重新生成',
    );
    vi.unstubAllGlobals();
  });
});
